### ISSUE TITLE
instructions

### ISSUE THREAD

**Issue by mnomansadiq** [Ayushkhodankar/Bed-Booking-System#1]
Can you please add the instructions on how to run this project?

**Comment by Ayushkhodankar** [comment]
> Can you please add the instructions on how to run this project?

You can run this project by :
1. Importing it on Eclipse IDE & by using MYSQL 8.0.22 version by creating tables in it.
2. Installing Apache tomcat server & running it on version7.
3. Check all the database URLs, root & password according to your setup.
4. Run on server in Eclipse IDE.

**Comment by mnomansadiq** [comment]
Where is the database script?

**Comment by Ayushkhodankar** [comment]
>The database script is in the controller package inside Dao classes.
